import"./assets/styles-BK7AYJoX.js";import{a as o,i as g}from"./assets/vendor-Cbhu4xvy.js";const a={categoryList:document.querySelector(".categories"),products:document.querySelector(".products"),notFound:document.querySelector(".not-found"),searchForm:document.querySelector(".search-form"),clearFormBtn:document.querySelector(".search-form__btn-clear")};function y(t){t.unshift("all");const e=t.map(r=>`<li class="categories__item">
        <button class="categories__btn" type="button">${r}</button>
      </li>`).join("");a.categoryList.insertAdjacentHTML("beforeend",e)}function n(t){if(a.products.innerHTML="",t.length===0){a.notFound.classList.add("not-found--visible");return}a.notFound.classList.remove("not-found--visible");const e=t.map(({id:r,thumbnail:s,title:d,brand:l,category:m,price:p})=>`<li class="products__item" data-id="${r}">
    <img class="products__image" src="${s}" alt="${d}"/>
    <p class="products__title">${d}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand:${l}</span></p>
    <p class="products__category">Category:${m} </p>
    <p class="products__price">Price: $${p} </p>
 </li>`).join("");a.products.insertAdjacentHTML("beforeend",e)}const c="https://dummyjson.com/products",f="https://dummyjson.com/products/category-list";async function _(){return(await o.get(f)).data}async function i(t=1){return(await o.get(`${c}?limit=12&skip=${(t-1)*12}`)).data.products}async function b(t,e=1){return(await o.get(`${c}/category/${t}?limit=12&skip=${(e-1)*12}`)).data.products}async function h(t,e=1){return(await o.get(`${c}/search?q=${t}`)).data.products}async function $(t){let e;const r=t.target;if(r.nodeName==="BUTTON"){const s=r.textContent;u(),r.classList.add("categories__btn--active"),s!=="all"?e=await b(s):e=await i(),n(e)}}async function L(t){t.preventDefault();const r=t.target.elements.searchValue.value.trim();if(!r){g.info({title:"Info",position:"topRight",message:"Enter a search term!"});return}const s=await h(r);u(),n(s)}async function v(){a.searchForm.elements.searchValue.value="";const t=await i();u(),n(t)}function u(){const t=document.querySelectorAll(".categories__btn--active");for(let e of t)e.classList.remove("categories__btn--active")}C();async function C(){y(await _()),n(await i())}a.categoryList.addEventListener("click",$);a.searchForm.addEventListener("submit",L);a.clearFormBtn.addEventListener("click",v);
//# sourceMappingURL=index.js.map
